compression: slow
threads: 8
vcodec: libx264
fps: 30
clip_time: 12.0
load_title: E:\FootballHighlights\Socal-OC-vs-SanDiego-20220518-1700-3.mp4
save_title: E:\FootballHighlights\Socal-OC-vs-SanDiego-20220518-1700-3-clip.mp4
save_path: clips
raw_times:
- '0329'
- '0343'
